# 나이브 베이즈 - 메일 스팸 여부 판단하기
- 조건부 확률 기반의 분류모델
- p(A|B) B라는 사건이 발생했을 때, A라는 사건이 발생할 확률을 구하기 위해 우변의 변수를 활용하는 것.

In [168]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [169]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data/spam.csv")

In [170]:
data.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [171]:
data["target"].unique()

array(['ham', 'spam'], dtype=object)

In [172]:
import string

In [173]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [174]:
sample_string = data['text'].loc[0]
sample_string

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [175]:
new_string=[]
for i in sample_string:
  if i not in string.punctuation:
    new_string.append(i)
new_string

['G',
 'o',
 ' ',
 'u',
 'n',
 't',
 'i',
 'l',
 ' ',
 'j',
 'u',
 'r',
 'o',
 'n',
 'g',
 ' ',
 'p',
 'o',
 'i',
 'n',
 't',
 ' ',
 'c',
 'r',
 'a',
 'z',
 'y',
 ' ',
 'A',
 'v',
 'a',
 'i',
 'l',
 'a',
 'b',
 'l',
 'e',
 ' ',
 'o',
 'n',
 'l',
 'y',
 ' ',
 'i',
 'n',
 ' ',
 'b',
 'u',
 'g',
 'i',
 's',
 ' ',
 'n',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't',
 ' ',
 'w',
 'o',
 'r',
 'l',
 'd',
 ' ',
 'l',
 'a',
 ' ',
 'e',
 ' ',
 'b',
 'u',
 'f',
 'f',
 'e',
 't',
 ' ',
 'C',
 'i',
 'n',
 'e',
 ' ',
 't',
 'h',
 'e',
 'r',
 'e',
 ' ',
 'g',
 'o',
 't',
 ' ',
 'a',
 'm',
 'o',
 'r',
 'e',
 ' ',
 'w',
 'a',
 't']

In [176]:
new_string = ''.join(new_string)
new_string

'Go until jurong point crazy Available only in bugis n great world la e buffet Cine there got amore wat'

In [177]:
# 특수기호 처리
def remove_punc(x):
  new_string=[]
  for i in x:
    if i not in string.punctuation:
      new_string.append(i)
  new_string = ''.join(new_string)
  return new_string

In [178]:
data['text']=data['text'].apply(remove_punc)
data['text']

0       Go until jurong point crazy Available only in ...
1                                 Ok lar Joking wif u oni
2       Free entry in 2 a wkly comp to win FA Cup fina...
3             U dun say so early hor U c already then say
4       Nah I dont think he goes to usf he lives aroun...
                              ...
5569    This is the 2nd time we have tried 2 contact u...
5570                  Will ü b going to esplanade fr home
5571    Pity  was in mood for that Soany other suggest...
5572    The guy did some bitching but I acted like id ...
5573                            Rofl Its true to its name
Name: text, Length: 5574, dtype: object

In [179]:
# 불용어 제거하기
# 저장된 문자열을 하나의 단어 단위로 리스트 변환
# 불용어 아니면 소문자로 지정
# 문자를 문자열로 합침

import nltk

from nltk.corpus import stopwords

In [180]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [181]:
# stopwords에서 제공되는 리스트를 의미
# 24개국어의 불용어 제공
# 한국어 불포함
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [182]:
# 특수기호 처리
def remove_word(x):
  nopewords=[]
  for i in x.split():
    if i.lower() not in stopwords.words('english'):
      nopewords.append(i)
  nopewords = ' '.join(nopewords)
  return nopewords

In [183]:
data['text']=data['text'].apply(remove_word)
data['text']

0       Go jurong point crazy Available bugis n great ...
1                                 Ok lar Joking wif u oni
2       Free entry 2 wkly comp win FA Cup final tkts 2...
3                     U dun say early hor U c already say
4             Nah dont think goes usf lives around though
                              ...
5569    2nd time tried 2 contact u U £750 Pound prize ...
5570                          ü b going esplanade fr home
5571                          Pity mood Soany suggestions
5572    guy bitching acted like id interested buying s...
5573                                       Rofl true name
Name: text, Length: 5574, dtype: object

In [184]:
# 텍스트를 숫자로 변환
data['target'] = data['target'].map({'spam':1,'ham':0})
data['target']

0       0
1       0
2       1
3       0
4       0
       ..
5569    1
5570    0
5571    0
5572    0
5573    0
Name: target, Length: 5574, dtype: int64

In [185]:
from sklearn.feature_extraction.text import CountVectorizer

In [186]:
x = data['text']
y = data['target']

In [187]:
cv = CountVectorizer()
cv.fit(x)
cv.vocabulary_

{'go': 3791,
 'jurong': 4687,
 'point': 6433,
 'crazy': 2497,
 'available': 1414,
 'bugis': 1881,
 'great': 3888,
 'world': 9184,
 'la': 4847,
 'buffet': 1879,
 'cine': 2214,
 'got': 3848,
 'amore': 1181,
 'wat': 8947,
 'ok': 5995,
 'lar': 4886,
 'joking': 4655,
 'wif': 9079,
 'oni': 6027,
 'free': 3577,
 'entry': 3160,
 'wkly': 9136,
 'comp': 2330,
 'win': 9093,
 'fa': 3296,
 'cup': 2553,
 'final': 3421,
 'tkts': 8380,
 '21st': 454,
 'may': 5335,
 '2005': 441,
 'text': 8217,
 '87121': 875,
 'receive': 6833,
 'questionstd': 6724,
 'txt': 8592,
 'ratetcs': 6776,
 'apply': 1267,
 '08452810075over18s': 71,
 'dun': 3011,
 'say': 7192,
 'early': 3031,
 'hor': 4222,
 'already': 1154,
 'nah': 5682,
 'dont': 2918,
 'think': 8291,
 'goes': 3805,
 'usf': 8741,
 'lives': 5050,
 'around': 1318,
 'though': 8310,
 'freemsg': 3585,
 'hey': 4118,
 'darling': 2617,
 'weeks': 9002,
 'word': 9170,
 'back': 1464,
 'id': 4343,
 'like': 5000,
 'fun': 3652,
 'still': 7860,
 'tb': 8147,
 'xxx': 9309,
 'std': 7835,
 'chgs': 2159,
 'send': 7288,
 '150': 353,
 'rcv': 6788,
 'even': 3207,
 'brother': 1848,
 'speak': 7706,
 'treat': 8517,
 'aids': 1100,
 'patent': 6226,
 'per': 6268,
 'request': 6946,
 'melle': 5378,
 'oru': 6091,
 'minnaminunginte': 5461,
 'nurungu': 5922,
 'vettam': 8805,
 'set': 7317,
 'callertune': 1964,
 'callers': 1963,
 'press': 6563,
 'copy': 2435,
 'friends': 3610,
 'winner': 9104,
 'valued': 8775,
 'network': 5758,
 'customer': 2566,
 'selected': 7274,
 'receivea': 6834,
 '900': 913,
 'prize': 6597,
 'reward': 7005,
 'claim': 2220,
 'call': 1945,
 '09061701461': 217,
 'code': 2281,
 'kl341': 4803,
 'valid': 8771,
 '12': 324,
 'hours': 4241,
 'mobile': 5520,
 '11': 313,
 'months': 5565,
 'entitled': 3157,
 'update': 8696,
 'latest': 4903,
 'colour': 2304,
 'mobiles': 5521,
 'camera': 1978,
 'co': 2270,
 '08002986030': 56,
 'im': 4373,
 'gonna': 3822,
 'home': 4188,
 'soon': 7656,
 'want': 8927,
 'talk': 8113,
 'stuff': 7933,
 'anymore': 1234,
 'tonight': 8439,
 'ive': 4569,
 'cried': 2514,
 'enough': 3148,
 'today': 8397,
 'six': 7508,
 'chances': 2096,
 'cash': 2039,
 '100': 291,
 '20000': 438,
 'pounds': 6500,
 'csh11': 2531,
 '87575': 879,
 'cost': 2448,
 '150pday': 360,
 '6days': 761,
 '16': 391,
 'tsandcs': 8552,
 'reply': 6938,
 'hl': 4154,
 'info': 4436,
 'urgent': 8719,
 'week': 8997,
 'membership': 5384,
 '100000': 294,
 'jackpot': 4578,
 '81010': 825,
 'tc': 8149,
 'wwwdbuknet': 9253,
 'lccltd': 4921,
 'pobox': 6412,
 '4403ldnw1a7rw18': 631,
 'searching': 7241,
 'right': 7017,
 'words': 9173,
 'thank': 8235,
 'breather': 1817,
 'promise': 6636,
 'wont': 9161,
 'take': 8104,
 'help': 4086,
 'granted': 3877,
 'fulfil': 3648,
 'wonderful': 9158,
 'blessing': 1688,
 'times': 8355,
 'date': 2626,
 'sunday': 8001,
 'xxxmobilemovieclub': 9310,
 'use': 8735,
 'credit': 2504,
 'click': 2242,
 'wap': 8932,
 'link': 5023,
 'next': 5777,
 'message': 5409,
 'httpwap': 4271,
 'xxxmobilemovieclubcomnqjkgighjjgcbl': 9311,
 'oh': 5988,
 'kim': 4770,
 'watching': 8952,
 'eh': 3081,
 'remember': 6905,
 'spell': 7722,
 'name': 5688,
 'yes': 9349,
 'naughty': 5714,
 'make': 5254,
 'wet': 9039,
 'fine': 3429,
 'that': 8245,
 'way': 8963,
 'feel': 3373,
 'gota': 3849,
 'england': 3139,
 'macedonia': 5216,
 'miss': 5480,
 'goalsteam': 3797,
 'news': 5772,
 'ur': 8716,
 'national': 5707,
 'team': 8163,
 '87077': 874,
 'eg': 3072,
 'trywales': 8550,
 'scotland': 7220,
 '4txtú120': 679,
 'poboxox36504w45wq': 6424,
 'seriously': 7310,
 'going': 3810,
 'try': 8547,
 'ha': 3959,
 'pay': 6237,
 'first': 3449,
 'da': 2582,
 'stock': 7864,
 'comin': 2320,
 'aft': 1062,
 'finish': 3435,
 'lunch': 5182,
 'str': 7890,
 'lor': 5108,
 'ard': 1294,
 'smth': 7594,
 'ffffffffff': 3391,
 'alright': 1156,
 'meet': 5363,
 'sooner': 7658,
 'forced': 3528,
 'eat': 3044,
 'slice': 7543,
 'really': 6814,
 'hungry': 4299,
 'tho': 8306,
 'sucks': 7971,
 'mark': 5290,
 'getting': 3750,
 'worried': 9190,
 'knows': 4815,
 'sick': 7451,
 'turn': 8573,
 'pizza': 6362,
 'lol': 5085,
 'always': 1166,
 'convincing': 2421,
 'catch': 2051,
 'bus': 1901,
 'frying': 3636,
 'egg': 3076,
 'tea': 8157,
 'eating': 3047,
 'moms': 5544,
 'left': 4944,
 'dinner': 2825,
 'love': 5134,
 'amp': 1183,
 'packing': 6149,
 'car': 2005,
 'ill': 4369,
 'let': 4967,
 'know': 4810,
 'theres': 8276,
 'room': 7062,
 'ahhh': 1091,
 'work': 9176,
 'vaguely': 8766,
 'wait': 8897,
 'thats': 8253,
 'clear': 2236,
 'sure': 8029,
 'sarcastic': 7166,
 'doesnt': 2890,
 'live': 5046,
 'us': 8731,
 'yeah': 9336,
 'apologetic': 1255,
 'fallen': 3323,
 'actin': 1000,
 'spoilt': 7750,
 'child': 2175,
 'caught': 2055,
 'till': 8349,
 'badly': 1470,
 'cheers': 2141,
 'tell': 8182,
 'anything': 1240,
 'fear': 3365,
 'fainting': 3313,
 'housework': 4246,
 'quick': 6725,
 'cuppa': 2555,
 'thanks': 8236,
 'subscription': 7960,
 'ringtone': 7026,
 'uk': 8623,
 'charged': 2108,
 '5month': 717,
 'please': 6391,
 'confirm': 2376,
 'replying': 6940,
 'yup': 9419,
 'look': 5096,
 'timings': 8362,
 'msg': 5609,
 'xuhui': 9305,
 'learn': 4933,
 '2nd': 520,
 'lesson': 4965,
 '8am': 902,
 'oops': 6045,
 'roommates': 7065,
 'done': 2915,
 'see': 7258,
 'letter': 4969,
 'decide': 2681,
 'hello': 4079,
 'hows': 4253,
 'saturday': 7182,
 'texting': 8225,
 'youd': 9384,
 'decided': 2682,
 'tomo': 8424,
 'trying': 8549,
 'invite': 4500,
 'pls': 6399,
 'ahead': 1089,
 'watts': 8961,
 'wanted': 8929,
 'weekend': 8999,
 'abiola': 952,
 'forget': 3534,
 'need': 5733,
 'crave': 2494,
 'sweet': 8060,
 'arabian': 1291,
 'steed': 7842,
 'mmmmmm': 5510,
 'yummy': 9414,
 '07732584351': 28,
 'rodger': 7051,
 'burns': 1898,
 'tried': 8526,
 'sms': 7588,
 'nokia': 5842,
 'camcorder': 1976,
 '08000930705': 52,
 'delivery': 2720,
 'tomorrow': 8427,
 'seeing': 7260,
 'hope': 4212,
 'man': 5264,
 'well': 9016,
 'endowed': 3129,
 'ltgt': 5167,
 'inches': 4404,
 'callsmessagesmissed': 1972,
 'calls': 1970,
 'didnt': 2795,
 'get': 3742,
 'hep': 4100,
 'immunisation': 4385,
 'nigeria': 5790,
 'fair': 3314,
 'hopefully': 4216,
 'tyler': 8602,
 'cant': 1996,
 'could': 2458,
 'maybe': 5337,
 'ask': 1346,
 'bit': 1663,
 'stubborn': 7921,
 'hospital': 4229,
 'kept': 4741,
 'telling': 8183,
 'weak': 8970,
 'sucker': 7969,
 'hospitals': 4230,
 'suckers': 7970,
 'thinked': 8292,
 'time': 8351,
 'saw': 7191,
 'class': 2228,
 'gram': 3869,
 'usually': 8752,
 'runs': 7109,
 'half': 3976,
 'eighth': 3084,
 'smarter': 7566,
 'gets': 3746,
 'almost': 1150,
 'whole': 9068,
 'second': 7245,
 'fyi': 3667,
 'ride': 7016,
 'morning': 5574,
 'hes': 4113,
 'crashing': 2493,
 'place': 6364,
 'wow': 9209,
 'never': 5763,
 'realized': 6812,
 'embarassed': 3109,
 'accomodations': 980,
 'thought': 8311,
 'liked': 5001,
 'since': 7478,
 'best': 1617,
 'seemed': 7264,
 'happy': 4010,
 'cave': 2059,
 'sorry': 7668,
 'give': 3772,
 'offered': 5969,
 'embarassing': 3110,
 'ac': 966,
 'sptv': 7773,
 'new': 5767,
 'jersey': 4622,
 'devils': 2773,
 'detroit': 2767,
 'red': 6857,
 'wings': 9102,
 'play': 6380,
 'ice': 4338,
 'hockey': 4172,
 'correct': 2440,
 'incorrect': 4415,
 'end': 3124,
 'mallika': 5263,
 'sherawat': 7371,
 'yesterday': 9364,
 'find': 3426,
 'lturlgt': 5170,
 'congrats': 2383,
 'year': 9338,
 'special': 7708,
 'cinema': 2215,
 'pass': 6214,
 '09061209465': 212,
 'suprman': 8027,
 'matrix3': 5323,
 'starwars3': 7822,
 'etc': 3193,
 'bx420ip45we': 1924,
 '150pm': 363,
 'later': 4901,
 'meeting': 5366,
 'reached': 6795,
 'yesgauti': 9357,
 'sehwag': 7271,
 'odi': 5961,
 'series': 7308,
 'pick': 6332,
 'burger': 1893,
 'move': 5593,
 'pain': 6156,
 'killing': 4767,
 'good': 3824,
 'joke': 4650,
 'girls': 3769,
 'situation': 7504,
 'seekers': 7261,
 'part': 6201,
 'checking': 2135,
 'iq': 4515,
 'took': 8446,
 'forever': 3531,
 'come': 2312,
 'double': 2933,
 'check': 2131,
 'hair': 3971,
 'dresser': 2968,
 'said': 7134,
 'wun': 9239,
 'cut': 2570,
 'short': 7412,
 'nice': 5783,
 'pleased': 6392,
 'advise': 1045,
 'following': 3508,
 'recent': 6837,
 'review': 7003,
 'mob': 5518,
 'awarded': 1433,
 '1500': 354,
 'bonus': 1732,
 '09066364589': 261,
 'song': 7650,
 'dedicated': 2692,
 'day': 2639,
 'dedicate': 2691,
 'valuable': 8773,
 'frnds': 3620,
 'rply': 7082,
 'complimentary': 2349,
 'trip': 8527,
 'eurodisinc': 3200,
 'trav': 8509,
 'acoentry41': 995,
 '1000': 292,
 'dis': 2838,
 '186': 400,
 '150morefrmmob': 356,
 'shracomorsglsuplt10': 7436,
 'ls1': 5157,
 '3aj': 583,
 'hear': 4054,
 'divorce': 2867,
 'barbie': 1501,
 'comes': 2316,
 'kens': 4739,
 'plane': 6371,
 'month': 5561,
 'wah': 8890,
 'lucky': 5175,
 'save': 7187,
 'money': 5549,
 'hee': 4070,
 'finished': 3437,
 'hi': 4123,
 'babe': 1452,
 'wanna': 8925,
 'something': 7636,
 'xx': 9306,
 'kkwhere': 4800,
 'youhow': 9387,
 'performed': 6275,
 'waiting': 8901,
 'machan': 5218,
 'cool': 2427,
 'gentleman': 3733,
 'dignity': 2815,
 'respect': 6967,
 'peoples': 6267,
 'much': 5628,
 'shy': 7446,
 'pa': 6144,
 'operate': 6052,
 'looking': 5100,
 'job': 4637,
 'tas': 8131,
 'earn': 3032,
 'ah': 1087,
 'stop': 7874,
 'urgnt': 8723,
 'real': 6805,
 'yo': 9374,
 'tickets': 8340,
 'one': 6023,
 'jacket': 4577,
 'used': 8736,
 'multis': 5639,
 'started': 7815,
 'requests': 6947,
 'came': 1977,
 'bed': 1571,
 'coins': 2288,
 'factory': 3304,
 'gotta': 3853,
 'nitros': 5814,
 'ela': 3089,
 'kanoil': 4715,
 'download': 2941,
 'wen': 9022,
 'don': 2913,
 'stand': 7803,
 'close': 2249,
 'you': 9380,
 'll': 5054,
 'another': 1218,
 'night': 5792,
 'spent': 7727,
 'late': 4896,
 'afternoon': 1064,
 'casualty': 2049,
 'means': 5349,
 'havent': 4036,
 'stuff42moro': 7934,
 'includes': 4408,
 'sheets': 7366,
 'smile': 7575,
 'pleasure': 6394,
 'trouble': 8533,
 'pours': 6502,
 'rain': 6749,
 'sum1': 7992,
 'hurts': 4314,
 'becoz': 1569,
 'someone': 7629,
 'loves': 5144,
 'smiling': 7579,
 'service': 7313,
 'representative': 6944,
 '0800': 48,
 '169': 393,
 '6031': 729,
 '10am9pm': 307,
 'guaranteed': 3927,
 '5000': 689,
 'planning': 6376,
 'buy': 1913,
 'lido': 4982,
 '530': 701,
 'show': 7427,
 'collected': 2297,
 'simply': 7475,
 'password': 6222,
 'mix': 5500,
 '85069': 860,
 'verify': 8801,
 'usher': 8743,
 'britney': 1838,
 'fml': 3498,
 'po': 6410,
 'box': 1767,
 '5249': 698,
 'mk17': 5503,
 '92h': 917,
 '450ppw': 642,
 'telugu': 8188,
 'moviewat': 5598,
 'abt': 961,
 'loads': 5062,
 'loans': 5064,
 'wk': 9132,
 'hols': 4186,
 'run': 7106,
 'forgot': 3539,
 'hairdressers': 3973,
 'appointment': 1271,
 'four': 3558,
 'shower': 7429,
 'beforehand': 1586,
 'cause': 2056,
 'prob': 6603,
 'coffee': 2283,
 'animation': 1205,
 'nothing': 5876,
 'else': 3103,
 'okay': 5996,
 'price': 6576,
 'long': 5092,
 'legal': 4947,
 'ave': 1420,
 'ams': 1187,
 'gone': 3819,
 '4the': 676,
 'driving': 2977,
 'test': 8211,
 'yet': 9365,
 'youre': 9397,
 'mean': 5345,
 'guess': 3935,
 'gave': 3701,
 'boston': 1754,
 'men': 5389,
 'changed': 2098,
 'search': 7240,
 'location': 5067,
 'nyc': 5932,
 'cuz': 2577,
 'signin': 7463,
 'page': 6152,
 'says': 7197,
 'umma': 8632,
 'life': 4985,
 'vava': 8787,
 'lot': 5118,
 'dear': 2663,
 'wishes': 9117,
 'birthday': 1661,
 'making': 5258,
 'truly': 8541,
 'memorable': 5386,
 'aight': 1102,
 'hit': 4145,
 'would': 9205,
 'ip': 4508,
 'address': 1019,
 'considering': 2394,
 'computer': 2356,
 'isnt': 4535,
 'minecraft': 5457,
 'server': 7312,
 'grumpy': 3919,
 'old': 6013,
 'people': 6266,
 'mom': 5541,
 'better': 1625,
 'lying': 5198,
 'jokes': 4652,
 'worry': 9193,
 'busy': 1907,
 'plural': 6404,
 'noun': 5885,
 'research': 6953,
 'dinnermsg': 2826,
 'cos': 2446,
 'things': 8290,
 'scared': 7204,
 'mah': 5242,
 'loud': 5129,
 'gent': 3731,
 'contact': 2399,
 'last': 4893,
 'weekends': 9000,
 'draw': 2955,
 'shows': 7435,
 '09064012160': 236,
 'k52': 4694,
 '12hrs': 337,
 '150ppm': 374,
 'wa': 8885,
 'openin': 6049,
 'sentence': 7301,
 'formal': 3542,
 'anyway': 1244,
 'juz': 4693,
 'tt': 8559,
 'eatin': 3046,
 'puttin': 6703,
 'weighthaha': 9007,
 'anythin': 1239,
 'happened': 4002,
 'entered': 3150,
 'cabin': 1931,
 'bday': 1554,
 'boss': 1753,
 'felt': 3383,
 'askd': 1347,
 'invited': 4501,
 'apartment': 1249,
 'went': 9025,
 'specially': 7713,
 'holiday': 4182,
 'flights': 3475,
 'inc': 4402,
 'operator': 6053,
 '0871277810910pmin': 121,
 '18': 396,
 'goodo': 3838,
 'must': 5659,
 'friday': 3603,
 'eggpotato': 3077,
 'ratio': 6778,
 'tortilla': 8465,
 'needed': 5735,
 'hmmmy': 4167,
 'uncle': 8639,
 'informed': 4440,
 'paying': 6243,
 'school': 7210,
 'directly': 2832,
 'food': 3516,
 'private': 6594,
 '2004': 440,
 'account': 984,
 'statement': 7825,
 '07742676969': 30,
 '786': 792,
 'unredeemed': 8681,
 'points': 6434,
 '08719180248': 169,
 'identifier': 4350,
 '45239': 644,
 'expires': 3276,
 '2000': 437,
 'caller': 1962,
 '5903': 706,
 'landline': 4873,
 '09064019788': 242,
 'box42wr29c': 1779,
 'applespairsall': 1265,
 'malarky': 5260,
 'todays': 8403,
 'voda': 8855,
 'numbers': 5918,
 'ending': 3126,
 '7548': 787,
 '350': 570,
 'award': 1432,
 'match': 5311,
 '08712300220': 103,
 'quoting': 6737,
 '4041': 615,
 'standard': 7804,
 'rates': 6775,
 'app': 1259,
 'sao': 7160,
 'mu': 5627,
 'predict': 6537,
 'üll': 9435,
 'buying': 1916,
 'knowyetunde': 4818,
 'hasnt': 4022,
 'sent': 7299,
 'bother': 1756,
 'sending': 7291,
 'involve': 4505,
 'shouldnt': 7422,
 'imposed': 4391,
 'apologise': 1256,
 'girl': 3765,
 'del': 2710,
 'bak': 1478,
 'sum': 7991,
 'lucyxx': 5179,
 'kkhow': 4794,
 'tmorrowpls': 8385,
 'accomodate': 979,
 'answer': 1221,
 'question': 6721,
 'sunshine': 8008,
 'quiz': 6732,
 'top': 8455,
 'sony': 7653,
 'dvd': 3020,
 'player': 6382,
 'country': 2465,
 'algarve': 1131,
 'ansr': 1220,
 '82277': 831,
 'sptyrone': 7774,
 'laid': 4864,
 'dogging': 2895,
 'locations': 5068,
 'direct': 2831,
 'join': 4645,
 'uks': 8626,
 'largest': 4890,
 'bt': 1864,
 'txting': 8597,
 'gravel': 3882,
 '69888': 755,
 'nt': 5906,
 'ec2a': 3049,
 '31pmsg150p': 561,
 'haf': 3965,
 'msn': 5620,
 'yijuehotmailcom': 9371,
 'rooms': 7066,
 'befor': 1585,
 'activities': 1006,
 'youll': 9391,
 'msgs': 5613,
 'chat': 2120,
 'svc': 8045,
 'hardcore': 4012,
 'services': 7314,
 '69988': 759,
 'age': 1072,
 'yr': 9410,
 'lazy': 4920,
 'type': 8604,
 'lect': 4941,
 'pouch': 6497,
 'sir': 7490,
 'mail': 5245,
 'swt': 8074,
 'nver': 5927,
 'tired': 8366,
 'little': 5045,
 'lovable': 5133,
 'persons': 6293,
 'cozsomtimes': 2479,
 'occupy': 5954,
 'biggest': 1642,
 'hearts': 4062,
 'gud': 3929,
 'ni8': 5780,
 'open': 6046,
 'ya': 9320,
 'dot': 2932,
 'whats': 9046,
 'staff': 7794,
 'taking': 8110,
 'replied': 6936,
 'randy': 6768,
 'sexy': 7330,
 'female': 3384,
 'local': 5066,
 'luv': 5188,
 'netcollex': 5754,
 'ltd': 5163,
 '08700621170150p': 73,
 'ummmawill': 8633,
 'inour': 4457,
 'begin': 1591,
 'qatar': 6708,
 'pray': 6530,
 'hard': 4011,
 'ki': 4755,
 'deleted': 2714,
 'sindu': 7480,
 'birla': 1657,
 'soft': 7616,
 'wine': 9100,
 'flowing': 3489,
 'nevering': 5764,
 'thk': 8300,
 'plaza': 6389,
 'typical': 8607,
 'everywhere': 3226,
 'dirt': 2835,
 'floor': 3483,
 'windows': 9097,
 'shirt': 7386,
 'sometimes': 7640,
 'mouth': 5592,
 'dream': 2959,
 'without': 9126,
 'chores': 2201,
 'joy': 4667,
 'lots': 5121,
 'tv': 8578,
 'exist': 3260,
 'hail': 3970,
 'mist': 5491,
 'become': 1567,
 'aaooooright': 941,
 'leaving': 4940,
 'house': 4242,
 'interview': 4487,
 'boy': 1784,
 'meare': 5352,
 'missing': 5484,
 'annoncement': 1211,
 'years': 9339,
 '07046744435': 21,
 'arrange': 1322,
 '0871277810810': 120,
 'keep': 4732,
 'safe': 7129,
 'envy': 3164,
 'everyone': 3220,
 'sees': 7268,
 'parentsi': 6192,
 'hand': 3985,
 'excited': 3248,
 'spend': 7725,
 'bootydelious': 1745,
 '32f': 566,
 'inviting': 4502,
 'friend': 3608,
 'yes434': 9351,
 'no434': 5821,
 'wwwsmsacubootydelious': 9273,
 'frnd': 3619,
 '62468': 737,
 'bangbabes': 1492,
 'order': 6077,
 'content': 2403,
 'goto': 3852,
 'bangb': 1491,
 'internetservice': 4486,
 'menu': 5397,
 'cultures': 2549,
 'module': 5534,
 '09061701939': 219,
 's89': 7119,
 'avoid': 1426,
 'missunderstding': 5489,
 'wit': 9122,
 'beloved': 1607,
 'ones': 6025,
 'escape': 3183,
 'fancy': 3335,
 'bridge': 1822,
 'needs': 5739,
 'lager': 4863,
 'completely': 2345,
 'formclark': 3546,
 'also': 1160,
 'utter': 8754,
 'waste': 8944,
 'axis': 1440,
 'bank': 1494,
 'hmmm': 4161,
 'hop': 4211,
 'muz': 5665,
 'discuss': 2851,
 'liao': 4974,
 'coming': 2321,
 'bloody': 1703,
 'hell': 4077,
 'believe': 1598,
 'surname': 8035,
 'mr': 5603,
 'clue': 2263,
 'spanish': 7700,
 'begins': 1592,
 'bath': 1524,
 'goodfine': 3828,
 'youve': 9404,
 'carlos': 2026,
 'mall': 5262,
 ...}

In [188]:
x = cv.transform(x)
print(x)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 47493 stored elements and shape (5574, 9437)>
  Coords	Values
  (0, 1181)	1
  (0, 1414)	1
  (0, 1879)	1
  (0, 1881)	1
  (0, 2214)	1
  (0, 2497)	1
  (0, 3791)	1
  (0, 3848)	1
  (0, 3888)	1
  (0, 4687)	1
  (0, 4847)	1
  (0, 6433)	1
  (0, 8947)	1
  (0, 9184)	1
  (1, 4655)	1
  (1, 4886)	1
  (1, 5995)	1
  (1, 6027)	1
  (1, 9079)	1
  (2, 71)	1
  (2, 441)	1
  (2, 454)	1
  (2, 875)	1
  (2, 1267)	1
  (2, 2330)	1
  :	:
  (5570, 3188)	1
  (5570, 3564)	1
  (5570, 3810)	1
  (5570, 4188)	1
  (5571, 5566)	1
  (5571, 6359)	1
  (5571, 7611)	1
  (5571, 7986)	1
  (5572, 999)	1
  (5572, 1665)	1
  (5572, 1916)	1
  (5572, 3103)	1
  (5572, 3577)	1
  (5572, 3701)	1
  (5572, 3950)	1
  (5572, 4343)	1
  (5572, 4480)	1
  (5572, 5000)	1
  (5572, 5777)	1
  (5572, 7636)	1
  (5572, 8731)	1
  (5572, 8997)	1
  (5573, 5688)	1
  (5573, 7052)	1
  (5573, 8538)	1

In [189]:
from sklearn.feature_extraction.text import CountVectorizer

In [190]:
data.loc[0]['text']

'Go jurong point crazy Available bugis n great world la e buffet Cine got amore wat'

In [191]:
print(cv.vocabulary_['go'])
print(cv.vocabulary_['jurong'])

3791
4687

In [196]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

In [197]:
model = MultinomialNB()
model.fit(X_train,y_train)
pred = model.predict(X_test)
accuracy_score(y_test,pred)

0.9856502242152466