In [1]:
# !pip install pandas==1.5.3
# !pip install seaborn==0.12.2

Requirement already satisfied: pandas==1.5.3 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from pandas==1.5.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from pandas==1.5.3) (2026.1.post1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from pandas==1.5.3) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from python-dateutil>=2.8.1->pandas==1.5.3) (1.17.0)
Requirement already satisfied: seaborn==0.12.2 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from seaborn==0.12.2) (1.23.5)
Requirement already satisfied: pandas>=0.25 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from seaborn==0.12.2) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from seaborn==0.12.2) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from pandas>=0.25->seaborn==0.12.2) (2026.1.post1)
Requirement already satisfied: six>=1.5 in c:\users\pc\anaconda3\envs\dl_gpu\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn==0.12.2) (1.17.0)

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
data = pd.read_csv('dataset/iris3.csv')
data.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
x = data.iloc[:,0:4].values
y = data.iloc[:,4].values

In [7]:
y = pd.get_dummies(y)
y

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [8]:
# 모델 생성

model =Sequential()
model.add(Dense(12,input_shape=(4,),activation='relu',name='Dense01'))
model.add(Dense(8,activation='relu',name='Dense02'))
model.add(Dense(3,activation='softmax',name='Dense03'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 Dense01 (Dense)             (None, 12)                60

 Dense02 (Dense)             (None, 8)                 104

 Dense03 (Dense)             (None, 3)                 27

=================================================================
Total params: 191
Trainable params: 191
Non-trainable params: 0
_________________________________________________________________

In [11]:
model.compile(loss='CategoricalCrossentropy',optimizer='adam',metrics=['accuracy'])

In [12]:
history = model.fit(x, y, epochs=100, batch_size=5)

Epoch 1/100
30/30 [==============================] - 2s 4ms/step - loss: 1.1021 - accuracy: 0.3333
Epoch 2/100
30/30 [==============================] - 0s 3ms/step - loss: 1.0373 - accuracy: 0.3867
Epoch 3/100
30/30 [==============================] - 0s 4ms/step - loss: 0.9887 - accuracy: 0.8200
Epoch 4/100
30/30 [==============================] - 0s 4ms/step - loss: 0.9345 - accuracy: 0.7667
Epoch 5/100
30/30 [==============================] - 0s 4ms/step - loss: 0.8760 - accuracy: 0.8267
Epoch 6/100
30/30 [==============================] - 0s 4ms/step - loss: 0.8257 - accuracy: 0.8600
Epoch 7/100
30/30 [==============================] - 0s 4ms/step - loss: 0.7823 - accuracy: 0.8867
Epoch 8/100
30/30 [==============================] - 0s 5ms/step - loss: 0.7575 - accuracy: 0.7933
Epoch 9/100
30/30 [==============================] - 0s 4ms/step - loss: 0.7253 - accuracy: 0.8867
Epoch 10/100
30/30 [==============================] - 0s 3ms/step - loss: 0.7033 - accuracy: 0.8667
Epoch 11/100
30/30 [==============================] - 0s 3ms/step - loss: 0.6820 - accuracy: 0.8733
Epoch 12/100
30/30 [==============================] - 0s 4ms/step - loss: 0.6622 - accuracy: 0.9267
Epoch 13/100
30/30 [==============================] - 0s 4ms/step - loss: 0.6423 - accuracy: 0.8800
Epoch 14/100
30/30 [==============================] - 0s 4ms/step - loss: 0.6256 - accuracy: 0.8933
Epoch 15/100
30/30 [==============================] - 0s 3ms/step - loss: 0.6090 - accuracy: 0.9067
Epoch 16/100
30/30 [==============================] - 0s 3ms/step - loss: 0.5946 - accuracy: 0.8933
Epoch 17/100
30/30 [==============================] - 0s 3ms/step - loss: 0.5804 - accuracy: 0.9333
Epoch 18/100
30/30 [==============================] - 0s 3ms/step - loss: 0.5738 - accuracy: 0.8733
Epoch 19/100
30/30 [==============================] - 0s 2ms/step - loss: 0.5549 - accuracy: 0.9400
Epoch 20/100
30/30 [==============================] - 0s 2ms/step - loss: 0.5438 - accuracy: 0.9200
Epoch 21/100
30/30 [==============================] - 0s 2ms/step - loss: 0.5344 - accuracy: 0.9200
Epoch 22/100
30/30 [==============================] - 0s 2ms/step - loss: 0.5145 - accuracy: 0.9200
Epoch 23/100
30/30 [==============================] - 0s 2ms/step - loss: 0.5001 - accuracy: 0.9267
Epoch 24/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 0.9067
Epoch 25/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4744 - accuracy: 0.9400
Epoch 26/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4620 - accuracy: 0.9267
Epoch 27/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4515 - accuracy: 0.9267
Epoch 28/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4401 - accuracy: 0.9333
Epoch 29/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4304 - accuracy: 0.9333
Epoch 30/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4216 - accuracy: 0.9467
Epoch 31/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4131 - accuracy: 0.9133
Epoch 32/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.9400
Epoch 33/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3935 - accuracy: 0.9333
Epoch 34/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3880 - accuracy: 0.9267
Epoch 35/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3781 - accuracy: 0.9467
Epoch 36/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3691 - accuracy: 0.9400
Epoch 37/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.9667
Epoch 38/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3545 - accuracy: 0.9467
Epoch 39/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3456 - accuracy: 0.9400
Epoch 40/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3388 - accuracy: 0.9400
Epoch 41/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.9467
Epoch 42/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.9400
Epoch 43/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3166 - accuracy: 0.9467
Epoch 44/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3112 - accuracy: 0.9600
Epoch 45/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3084 - accuracy: 0.9467
Epoch 46/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3029 - accuracy: 0.9400
Epoch 47/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2938 - accuracy: 0.9533
Epoch 48/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2908 - accuracy: 0.9600
Epoch 49/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2853 - accuracy: 0.9467
Epoch 50/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2781 - accuracy: 0.9533
Epoch 51/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2717 - accuracy: 0.9600
Epoch 52/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2670 - accuracy: 0.9533
Epoch 53/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2627 - accuracy: 0.9533
Epoch 54/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2591 - accuracy: 0.9467
Epoch 55/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2567 - accuracy: 0.9533
Epoch 56/100
30/30 [==============================] - 0s 3ms/step - loss: 0.2483 - accuracy: 0.9667
Epoch 57/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2562 - accuracy: 0.9467
Epoch 58/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2508 - accuracy: 0.9333
Epoch 59/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2403 - accuracy: 0.9667
Epoch 60/100
30/30 [==============================] - 0s 1ms/step - loss: 0.2336 - accuracy: 0.9667
Epoch 61/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2307 - accuracy: 0.9600
Epoch 62/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2242 - accuracy: 0.9667
Epoch 63/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2216 - accuracy: 0.9667
Epoch 64/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2172 - accuracy: 0.9733
Epoch 65/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2162 - accuracy: 0.9667
Epoch 66/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2125 - accuracy: 0.9667
Epoch 67/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2093 - accuracy: 0.9667
Epoch 68/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2061 - accuracy: 0.9600
Epoch 69/100
30/30 [==============================] - 0s 2ms/step - loss: 0.2076 - accuracy: 0.9600
Epoch 70/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1961 - accuracy: 0.9667
Epoch 71/100
30/30 [==============================] - 0s 1ms/step - loss: 0.1963 - accuracy: 0.9733
Epoch 72/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1934 - accuracy: 0.9667
Epoch 73/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1945 - accuracy: 0.9667
Epoch 74/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1862 - accuracy: 0.9733
Epoch 75/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1860 - accuracy: 0.9733
Epoch 76/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1843 - accuracy: 0.9733
Epoch 77/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1787 - accuracy: 0.9667
Epoch 78/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1806 - accuracy: 0.9600
Epoch 79/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1751 - accuracy: 0.9667
Epoch 80/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1735 - accuracy: 0.9733
Epoch 81/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1727 - accuracy: 0.9667
Epoch 82/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1688 - accuracy: 0.9733
Epoch 83/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1667 - accuracy: 0.9667
Epoch 84/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1671 - accuracy: 0.9600
Epoch 85/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1628 - accuracy: 0.9667
Epoch 86/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1609 - accuracy: 0.9733
Epoch 87/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1608 - accuracy: 0.9667
Epoch 88/100
30/30 [==============================] - 0s 1ms/step - loss: 0.1669 - accuracy: 0.9533
Epoch 89/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1556 - accuracy: 0.9667
Epoch 90/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1539 - accuracy: 0.9733
Epoch 91/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1512 - accuracy: 0.9733
Epoch 92/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1510 - accuracy: 0.9733
Epoch 93/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.9800
Epoch 94/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1464 - accuracy: 0.9733
Epoch 95/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1499 - accuracy: 0.9667
Epoch 96/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1425 - accuracy: 0.9667
Epoch 97/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1472 - accuracy: 0.9667
Epoch 98/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1473 - accuracy: 0.9600
Epoch 99/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1532 - accuracy: 0.9667
Epoch 100/100
30/30 [==============================] - 0s 2ms/step - loss: 0.1390 - accuracy: 0.9800

In [13]:
print("Accuracy : %4f" % (model.evaluate(x, y))[1])

5/5 [==============================] - 0s 7ms/step - loss: 0.1346 - accuracy: 0.9733
Accuracy : 0.973333

In [14]:
m ,acc = model.evaluate(x, y)
print('정확도 : %.2f' %(acc*100))
print(m)

5/5 [==============================] - 0s 6ms/step - loss: 0.1346 - accuracy: 0.9733
정확도 : 97.33
0.1346399337053299

In [31]:
# 새로운 데이터로 예측하기

new_flower = np.array([[5.1,3.5,1.4,0.2]])

pred = model.predict(new_flower)
s = ['setosa','versicolor','virginica']
pred_s = s[np.argmax(pred)]

print("예측 후보 :",s)
print('예측 확률 :',pred)
print("예측 결과 :",pred_s)

1/1 [==============================] - 0s 7ms/step
예측 후보 : ['setosa', 'versicolor', 'virginica']
예측 확률 : [[9.9961865e-01 3.8129970e-04 6.6923818e-09]]
예측 결과 : setosa