In [4]:
import pandas as pd
import numpy as np

In [3]:
pd.DataFrame({'A':[1,2,3]})

   A
0  1
1  2
2  3

In [3]:
a = 1
print(a)
a

1

1

# Basic data structures in pandas

- **series** : 모든 유형의 데이터를 보유하는 1차원 레이블 배열

- **DataFreame** : 행과 열로 구성된 표나 2차원 배열처럼 데이터를 보관하는 2차원적 데이터 구조

# Object creation

In [5]:
# Series으로 기본값 생성

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
# DataFrame으로 기본값 생성